### ISSUE TITLE
OPDS sample URLs (not an issue, just a heads-up / FYI)

### ISSUE THREAD

**Issue by danielweck** [NYPL-Simplified/opds-web-client#92]
Fun project, thanks for sharing! I've been playing with a few OPDS URLs, so I thought I'd let you know. I occasionally use the following aggregated OPDS feeds to test Readium:
https://dl.dropboxusercontent.com/u/585153/Readium/ebooks/opds_links.atom

The Readium "cloud reader" is a pure-client app (no server-side code, just a static HTTP host). It implements a _very_ basic OPDS browser, but does handle direct EPUB acquisition links (loading through a CORS proxy, when necessary), and exposes external hyperlinks for indirect acquisitions. Here's an example using the above OPDS link (you may have to wait a few seconds when loading EPUBs because of network + proxy latency):
https://readium.firebaseapp.com/?epubs=https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F585153%2FReadium%2Febooks%2Fopds_links.atom

We also have a bunch of additional OPDS feeds, but note that we rely on an OPDS content-type "hack" (`application/epub` instead of `application/epub+zip` in acquisition links) so that we can reference "exploded" EPUB archives directly from HTTP root URLs (e.g. GitHub repositories / "raw git").

1) IDPF sample EPUBs:
https://readium.firebaseapp.com/epub_content/epub_samples.opds
Readium cloud-reader link:
https://readium.firebaseapp.com/?epubs=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_samples.opds

2) IDPF EPUB testsuite:
https://readium.firebaseapp.com/epub_content/epub_testsuite.opds
Readium cloud-reader link:
https://readium.firebaseapp.com/?epubs=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_testsuite.opds

3) IDPF EPUB widget (embedded scriptable components) experiments:
https://readium.firebaseapp.com/epub_content/epub_widgets.opds
Readium cloud-reader link:
https://readium.firebaseapp.com/?epubs=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_widgets.opds

4) EDUPUB (EPUB for Education) samples:
https://readium.firebaseapp.com/epub_content/epub_edu.opds
Readium cloud-reader link:
https://readium.firebaseapp.com/?epubs=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_edu.opds

5) the default Readium "cloud reader" feed (which combines acquisition + navigation for the above 1,2,3 feeds ... I know, it's not OPDS-legal, but it works fine for us :)
https://readium.firebaseapp.com/epub_content/epub_library.opds
Readium cloud-reader link:
https://readium.firebaseapp.com/?epubs=https%3A%2F%2Freadium.firebaseapp.com%2Fepub_content%2Fepub_library.opds

6) a list of free EPUB3 Media Overlays (audio) ebooks from ReadBeyond:
https://dl.dropboxusercontent.com/u/585153/Readium/ebooks/readbeyond.opds
Readium cloud-reader link:
https://readium.firebaseapp.com/?epubs=https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F585153%2FReadium%2Febooks%2Freadbeyond.opds

Feel free to delete this "issue", I just wanted to give you a heads-up :)

**Comment by aslagle** [comment]
Thanks! The aggregated feed will be very useful :)

**Comment by danielweck** [comment]
Example:
http://opds-browser-demo.herokuapp.com/?collection=https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F585153%2FReadium%2Febooks%2Fopds_links.atom

**Comment by danielweck** [comment]
Dropbox links are dead, closing issue.
